// Development-time review index only. Never import this from runtime code.
export const authorities = [
  { title: 'Product Design', url: 'https://docs.google.com/document/d/1rTZiWCVA_7uPSBgMYyFycpPqJ8313Xu7knKF3ZswNcs/edit', checked: '2026-09-28', revision: '2026-09-27' },
  { title: 'Teacher Workspace', url: 'https://docs.google.com/document/d/1uawcuRFIhf7fX6Z4E8KeiwMYF-MCicx7Qm6JNcvUkRU/edit', checked: '2026-09-28', revision: '2026-09-27' },
  { title: 'Runtime Architecture', url: 'https://docs.google.com/document/d/1btwXR3h6AewQBXB4gEaeR-Co7rvH5vQbXHZ2NbRwZtE/edit', checked: '2026-09-28', revision: '2026-09-27' },
];
export type Task = { id: string; title: string; design: string; implementation: string; basis: string;
  responsibility: string; input: string; output: string; trigger: string; gaps: string;
  refs: { file: string; symbol: string; kind: 'instructions' | 'builder' | 'schema/parser' | 'host' | 'configuration' }[];
  evaluation: string; deterministic: string; };
const ref = (file: string, symbol: string, kind: Task['refs'][number]['kind']): Task['refs'][number] => ({ file, symbol, kind });
export const tasks: Task[] = [
  { id: 'teaching-understanding', title: '实时讲授理解：动作、stance 与关系', design: '已确认目标', implementation: '已接入',
    basis: 'Product §§3–8；Runtime §21', responsibility: '判断新证据如何建立、发展、修订或回指已有教学对象；primary 与 relation 为关联阶段。',
    input: '有角色依据的 Final、待续接片段、Cue/part 版本、来源候选及 coverage。', trigger: '运行期有界 inspection；relation 仅在有资格时续接。',
    output: '有界提案 → compileProposal → LessonStore.accept；Host 分配身份并重检来源、权限、版本。',
    gaps: '单次评测不是整堂课模拟；候选缺失或容量截断不能算模型误判；compound 仍 exploratory。',
    refs: [ref('prompts/jev-semantic/instructions.ts', '*（静态导出及候选 condition）', 'instructions'), ref('src/alive/inspection.ts', 'buildSemanticRequest / operationCandidates / captureRelation', 'builder'),
      ref('src/alive/inspection.ts', 'validateSemanticInput / parseSemanticJudgment / compileProposal', 'schema/parser'), ref('src/alive/journal.ts', 'LessonStore.accept', 'host'), ref('server/semantic-jev.ts', 'inspectWithJev', 'host')],
    evaluation: 'npm run eval:jev:validate；npm run test:jev-evals；授权后 npm run eval:jev', deterministic: 'extraction/provider/loader + runtime tests（执行结果见交付记录）' },
  { id: 'accepted-expression', title: '已接受内容的表达与组织', design: '已确认目标', implementation: '部分接入',
    basis: 'Runtime §§11–12；Teacher Workspace §4', responsibility: '忠实整理选定内容；当前只实现单 Cue Presentation V1。',
    input: '已选 sourceText、完整 Final、最多两条必要消歧上下文。', trigger: '已启用且有效的 current Cue；whole-Final 重建成功且不超输入限制。',
    output: 'source 或 1–3 个 text/list/chain blocks；只写派生显示，不写 CueRevision。',
    gaps: '旧 student reading 措辞原样保留；current-only 与 whole-Final 是现有限制，不是整个 LLM 长期职责。未实现通用离屏产物保存。',
    refs: [ref('prompts/presentation-v1/request.ts', 'PRESENTATION_INSTRUCTIONS / buildPresentationRequest', 'instructions'), ref('prompts/presentation-v1/request.ts', 'validatePresentationInput / parsePresentationResponse', 'builder'),
      ref('src/refinement/presentation.ts', 'presentationSchema / parsePresentationReply', 'schema/parser'), ref('src/refinement/input.ts', 'presentationInput', 'host'), ref('src/refinement/cue-refinement.ts', 'sync / pump / canPublish / run', 'host'),
      ref('server/openai-refinement-api.ts', 'openaiRefinementApiPlugin', 'host'), ref('server/runtime-config.ts', 'parseRuntimeConfig.refinement', 'configuration')],
    evaluation: 'npm run eval:presentation:validate；npm run test:prompt-workspace；授权后 npm run eval:presentation', deterministic: '迁移前 HTTP 快照、共享 parser、输入资格、loader；语义人工审查另计' },
  { id: 'multi-cue-expression', title: '多 Cue 组合表达', design: '已确认目标', implementation: '未实现', basis: 'Runtime §§11–12；Product §6',
    responsibility: '把多个已接受对象组织成对比、回顾等独立表达。', input: '全部选定 Cue 版本、实际依赖关系与内容范围。', trigger: '待定，不自动对每个 Cue 启动。',
    output: '独立派生产物；不合并 canonical 身份。', gaps: '尚无生产 builder、schema、provider 或保存链路；触发及产物合同实现待定。', refs: [], evaluation: '不可运行；NOT_RUN', deterministic: 'NOT_RUN' },
  { id: 'source-semantic-review', title: '原讲授的语义复核与后台补认', design: '已确认目标', implementation: '未实现', basis: 'Runtime §11、§21；Teacher Workspace §2',
    responsibility: '依据原讲授补认遗漏条件、明确纠正、教学角色和有依据的关系。', input: '原始证据、supplementalReviewEvidence、明确 read/write scope 与版本。', trigger: '按 operation type 验证和启用，策略与门槛待定。',
    output: '有界 semantic proposal；启用后经唯一接受入口追加版本，未获资格只保留审阅。', gaps: '未启用通用后台语义写入；不强制 Jev 逐项批准，也不跳过 Host。',
    refs: [ref('src/alive/journal.ts', 'LessonStore.accept（已有通用接受边界，并非后台服务）', 'host')], evaluation: '不可运行；NOT_RUN', deterministic: '后台任务 NOT_RUN；已有接受边界独立测试' },
  { id: 'retrieval-assistance', title: '索引／检索与对齐辅助', design: '条件式允许', implementation: '未实现（模型辅助）', basis: 'Runtime §§10–11；Product §7',
    responsibility: '必要时生成派生别名／摘要、改写自由查询或提出关系与资产对齐候选。', input: '来源锚点、查询意图、候选范围、固定 Pack release/version/digest。', trigger: '条件式使用；不假定每一检索环节都调用模型。',
    output: '派生索引、查询或候选；命中后返回原依据，正式 binding 另行接受。', gaps: '本课确定性 lookup 已存在；模型辅助与 Pack 查询并未因此完成。模型、schema、触发待定。',
    refs: [ref('src/alive/projection.ts', 'lookupLessonCues（确定性查找）', 'host')], evaluation: '模型辅助不可运行；NOT_RUN', deterministic: '已有 lookup 测试不证明模型能力' },
  { id: 'cue-enrich', title: 'Cue 增强 ENRICH', design: '已确认目标', implementation: '未实现（后端）', basis: 'Teacher Workspace §§4–5、7–9；Product §1',
    responsibility: '为选定 Cue 提供新例子、类比、批注、替代表达、混淆说明与参考。', input: '真实 Cue 版本、来源、必要上下文；可选教学背景与已读取材料。', trigger: '教师按需请求；自动批注仍待验证。',
    output: '标为补充／参考的派生产物，绑定真实来源与版本；收藏不修改讲授历史。', gaps: 'UI 入口不等于后端可用；引用读取、产物保存/删除/失效未接入。模型与 prompt 待定。', refs: [ref('src/ui/TraceView.tsx', 'Reference disabled placeholder', 'host')], evaluation: '不可运行；NOT_RUN', deterministic: 'NOT_RUN' },
  { id: 'lesson-rework', title: '整课建议 REWORK', design: '已确认目标', implementation: '未实现（后端）', basis: 'Teacher Workspace §§6–9；Runtime 附录 D',
    responsibility: '提出课序、转接、对比与组织的备选及取舍，帮助备课。', input: '声明范围的整课快照：证据、Cue 版本、关系、实际顺序与缺口。', trigger: '教师请求；不要求先完成 ENRICH。',
    output: '独立建议或作者草稿；原流程与建议流程并存，不重排历史、不自动合并 Cue。', gaps: '范围快照、依赖与作者编辑保存未实现；不能只读取最后一个 current Cue。', refs: [ref('src/ui/TraceView.tsx', 'REWORK disabled placeholder', 'host')], evaluation: '不可运行；NOT_RUN', deterministic: 'NOT_RUN' },
  { id: 'review-only', title: '受限复核：身份重组／外部学科核查', design: '权限边界已定义', implementation: '未实现', basis: 'Runtime §11；Teacher Workspace §2',
    responsibility: '提出拆分／合并或外部核查意见，供人审阅。', input: '对象及版本、课堂依据；外部资料独立标明。', trigger: '待定；不是本轮业务开发排期。',
    output: 'review-only；不迁移引用、不改身份、不用外部答案覆盖原话。', gaps: '无生产 prompt/schema/provider；如何审阅、采纳与保留差异待定。', refs: [], evaluation: '不可运行；NOT_RUN', deterministic: 'NOT_RUN' },
  { id: 'trace-narration', title: 'TRACE 命名／归纳／叙述', design: '可选派生能力', implementation: '未实现（可选）', basis: 'Teacher Workspace §7；Runtime 附录 D',
    responsibility: '如将来使用模型，可辅助命名、归纳或叙述已接受轨迹。', input: '带来源与范围的 AcceptedEvent/Cue 记录。', trigger: '可选、待定；不是必做 TraceSummary 服务。',
    output: '另存带来源派生叙述，不替代原始 Cue、事件与确定性 TRACE。', gaps: '基础 TRACE 不需要模型；此条无 prompt、模型或评测承诺。', refs: [], evaluation: '不可运行；NOT_RUN', deterministic: 'NOT_RUN' },
  { id: 'legacy-selection', title: '历史／工具：structured-v3 选择', design: '历史留档', implementation: '已接入（工具／兼容）', basis: 'Runtime 附录 D.5；代码路径核查',
    responsibility: '旧单显示 Cue 的 QUIET / NEW_CUE / UPDATE_CURRENT 选择。', input: '近期证据、完整候选 span、当前显示 Cue。', trigger: 'scripts/replay.ts 的 legacy Jev 模式及 /api/jev/decide；当前产品实时路径是 /inspect。',
    output: '旧动作／候选 ID，经旧 parser；不等同原生 Alive 语义提案。', gaps: '保留真实可达入口；不是新的教师工作台规则，无新增 live eval。',
    refs: [ref('src/decision/jev-context.ts', 'buildJevRequest（静态与动态措辞唯一源）', 'instructions'), ref('src/decision/jev-choice.ts', 'buildJevOptions / parseJevChoice', 'schema/parser'), ref('server/jev-api.ts', '/api/jev/decide /api/jev/inspect', 'host'), ref('scripts/replay.ts', 'legacy replay', 'host')],
    evaluation: '既有 unit/replay tests；不新增付费入口', deterministic: '现有回归测试（不是新模型行为结果）' },
  { id: 'speech-recognition', title: '相邻依赖：Speechmatics 识别', design: '已确认依赖', implementation: '供应商能力／配置', basis: 'Product §3；代码核查',
    responsibility: '供应商把音频转为 partial/Final；本仓库无自有识别 prompt。', input: '音频及识别配置。', trigger: '用户开启采集。',
    output: 'provider-native Final；角色权限与语义接受仍由 Host 管。', gaps: '不编造供应商内部指令；ASR 置信不等于来源权限。',
    refs: [ref('voice_gateway/gateway.py', 'Speechmatics gateway', 'host'), ref('voice_gateway/config.py', 'GatewayConfig.voice_config / diagnostics', 'configuration')], evaluation: 'npm run test:voice（模拟供应商；不证明识别质量）', deterministic: 'Voice tests' },
];
